apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-java-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - image: test-java-app
          imagePullPolicy: IfNotPresent
          name: test-java-app
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 180
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 2000m
              memory: 1024M