name: Compile&Test

on:
  push:
    branches: [ main ]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  mvn-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
        architecture: x64
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: m2
    - name: Compile
      run: mvn clean compile
    - name: Test
      id: test
      run: mvn test
    - name: Clean
      run: mvn clean
    - uses: LouisBrunner/checks-action@v1.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Compile&Test
        conclusion: ${{ job.status }}
